### ISSUE TITLE
Bug when subscribe on derived query

### ISSUE THREAD

**Issue by stfy** [timdeschryver/rx-query#1]
Hello, I am impressed of this library. And when i am tried to do something similar with, i found a bug. 

I need to do 2 requests in order, second request params is deriving from response of first response. 

_example: https://codesandbox.io/s/condescending-cookies-nn778?file=/src/app/app.component.ts_

Expected behavior: loaded data with id 1 -> load data with id + 5 

Behavior: emits previous value on second emit of high order query

**Comment by stfy** [comment]
I have found a decision, it's my mistake. I am only needs replay last high order query

**Comment by timdeschryver** [comment]
@stfy If I understand the question correctly, you'll have to "wait" until the first query is in the "success" state. Because they key `key` is used, its value will change when it's refreshing on each interval.

I believe the derived param should look like this

```ts
  derivedParam = this.qq.pipe(
	// 👇 this line is added
    filter(p => p.status === 'success'),
    pluck("data"),
    filter((a) => !!a),
    pluck("id"),
    map((id) => {
      console.log(id);
      return id + 5;
    })
  );
```

Thanks for your kind words, and congrats on being creating the first issue 🎉

**Comment by stfy** [comment]
> @stfy If I understand the question correctly, you'll have to "wait" until the first query is in the "success" state. Because they key `key` is used, its value will change when it's refreshing on each interval.
> 
> I believe the derived param should look like this
> 
> ```ts
>   derivedParam = this.qq.pipe(
> 	// 👇 this line is added
>     filter(p => p.status === 'success'),
>     pluck("data"),
>     filter((a) => !!a),
>     pluck("id"),
>     map((id) => {
>       console.log(id);
>       return id + 5;
>     })
>   );
> ```
> 
> Thanks for your kind words, and congrats on being creating the first issue 🎉

I wanted to subscribe second query after first being subscribed. And when i do this, second query emits value only when first query changed again. I resolve it by add shareReplay to first query. Thanks for helping. 

I try to integrate rx-query and redux-like architecture. For example, if rx-query triggers by newest params an integration dispatches change state

**Comment by timdeschryver** [comment]
@stfy feel free to provide feedback to stabilize the API of this library
