### ISSUE TITLE
README is missing a tagline

### ISSUE THREAD

**Issue by shairez** [timdeschryver/rx-query#11]
Looks like a great library @timdeschryver !

When reading the README to figure out what this lib actually does, I was missing the first "one line description" like react-query has - 

"Hooks for fetching, caching and updating asynchronous data in React"

So something like that.. but for this library 😄

**Comment by timdeschryver** [comment]
Thanks for the tip @shairez , see 9d8ec8e for the tagline.
I accidently pushed already, but feel free to tell me if it's bad or if it's missing something.

**Comment by shairez** [comment]
LGTM 🤜🤛💥
