### ISSUE TITLE
refetchOnWindowFocus and refetchOnReconnect are true by default

### ISSUE THREAD

**Issue by Quraian** [timdeschryver/rx-query#12]
However, I can see that they are supposed to be false according to the type definitions. Personally I prefer refetchOnWindowFocus to be false, but this is up to the library author and the other users.

**Comment by timdeschryver** [comment]
Hi, thanks for opening this issue!
For now, I want to keep the default to `true` (react-query also does this).
We could provide a `setConfig` method, so you can set the default for all your queries.
That shouldn't be that hard to implement.

**Comment by Quraian** [comment]
That's your call, however, the type definitions have to be fixed then :)

**Comment by timdeschryver** [comment]
Yea, you're right about that 😅

**Comment by timdeschryver** [comment]
Should be resolved in v0.0.16 🚀
