### ISSUE TITLE
Feature request: Mutate function

### ISSUE THREAD

**Issue by IanIsFluent** [timdeschryver/rx-query#14]
I can see that queries have a `mutator` - but I generally want mutation and queries to be separate bits of code (command/query segregation etc. etc) - how would I do that with this library?

Note: react-query has `useQuery` and `useMutation` - totally separate, and what I was expecting to see (obviously i'd need to keep the associated query's cache up-to-date...)

**Comment by timdeschryver** [comment]
I agree. 

The reasoning why I added `mutate` was so rx-query can refresh the data automatically (which was something I needed in a project). With react-query, the user has to invalidate and refresh the cache(s) manually and thus the user needs to know the cache key before doing that.

I didn't add `useMutation` because I believe that Angular is perfectly capable of making these, and with RxJS you can easily hook into the stream to invalidate and refresh the cache.

**Comment by IanIsFluent** [comment]
Oh, OK! The reason I want `useMutation` is to get your consistent `Pending` type around it. So I can check the `.status`. It seems strange for me to re-implement that, and try to make it all match as closely as possible?

**Comment by timdeschryver** [comment]
That's a valid argument to have (that I didn't think of) 😅

**Comment by IanIsFluent** [comment]
> Hey, Is there a way to do manual query invalidation like: https://react-query.tanstack.com/guides/invalidations-from-mutations ? It will be nice to be able to refresh specific query or queries after mutation is done. I looked in source code and it seems that right now you can't update cache from outside.

according to Tim:
> with RxJS you can easily hook into the stream to invalidate and refresh the cache.

**Comment by tvildo** [comment]
> > Hey, Is there a way to do manual query invalidation like: https://react-query.tanstack.com/guides/invalidations-from-mutations ? It will be nice to be able to refresh specific query or queries after mutation is done. I looked in source code and it seems that right now you can't update cache from outside.
> 
> according to Tim:
> 
> > with RxJS you can easily hook into the stream to invalidate and refresh the cache.

Can you paste some example of how to do what he mentioned ?

**Comment by timdeschryver** [comment]
That's correct @tvildo
