### ISSUE TITLE
Unable to integration test - `Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)`

### ISSUE THREAD

**Issue by IanIsFluent** [timdeschryver/rx-query#17]
I've been trying to integration test with this library (I'd rather only write integration tests!) - but I assume because of the auto-refresh functionality, there doesn't seem to be a way to get code which includes calls made with this library to finish in a Karma/Jasmine test!

I've tried all the usual candidates: `async, done(), fakeAsync, flush(), flushMicrotasks, discardPeriodicTasks();` but there doesn't seem to be a way to kill whatever is waiting on a response ☹️  if my options are using this library or writing integration tests, then I think I'm going to have to stop using RxQuery 😢 

(Sorry for all the bug reports!)

**Comment by timdeschryver** [comment]
Hi, do you have a reproduction of this?
This method isn't documented, but have you tried using `resetQueryCache` before each test?

```ts

beforeEach(() => {
	resetQueryCache();
});

```

**Comment by IanIsFluent** [comment]
Thanks @timdeschryver, but resetQueryCache didn't seem to help. The problem is always in the next test after the one which is using rx-query. Consistently with the error message from the title: `Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)`

**Comment by timdeschryver** [comment]
I assume the tests are running in the browser (am I correct?).
If that's the case, the only thing I can think of is that it gets the focus and thus it's refreshing the data.
Have you tried running in headless mode?

**Comment by IanIsFluent** [comment]
They are! And I have not. Focus? I think it doesn't need the focus for the async operation of the 'refresh' not to have finished...

**Comment by denisogolubev** [comment]
I have caught the same error because I used the setTimeout function in the component. Example:

```
  ngOnInit(): void {
    this.changeState();
  }
  
  private changeState(): void {
    setTimeout(() => this.state = StateEnum.IN_PROGRESS, 10000);
  }
```
When I changed the timeout from 10000ms to 0 or less than 5000ms (DEFAULT_TIMEOUT_INTERVAL) all tests were passed.
