### ISSUE TITLE
Refetch without refreshQuery

### ISSUE THREAD

**Issue by adnanebrahimi** [timdeschryver/rx-query#19]
Hi,

When I try to call this function again the status of the previous call be shown and then the status will change to `refreshing`.
Can you help me what is the correct implementation??

```
someMethod() {
    query(
          'updateUserBilling',
          () => this.store.dispatch(new UpdateUserBillingAction(user)),
          { retries: 0, refetchOnWindowFocus: false, refetchOnReconnect:false}
        ).pipe(
              tap(query => {
              console.log(query.status);
        });
}
```

for the first try the output will be:

```
// loading

// success
```

for the second try the output will be:

```
// success

// refreshing

// success
```

**Comment by timdeschryver** [comment]
Can you create a reproduction for this please @adnanebrahimi ?
Thanks in advance!

**Comment by adnanebrahimi** [comment]
@timdeschryver 
https://stackblitz.com/edit/angular-ivy-wczlx8?devtoolsheight=33&file=src/app/app.component.html

**Comment by timdeschryver** [comment]
Thanks for the reproduction @adnanebrahimi , I'll try to take a look at it next week.
I don't write it that way tho, what I do is I setup the stream and when I want to refresh the data, I use `refreshQuery(key)`.
I've updated the reproduction at https://stackblitz.com/edit/angular-ivy-qpkgek?file=src%2Fapp%2Fapp.component.ts

**Comment by adnanebrahimi** [comment]
Thank you tim. 

But as you can see I didn't want to make a stream.

**Comment by timdeschryver** [comment]
@adnanebrahimi I didn't find the time to take a look into this, feel free to take a look yourself (it's a low prio for me) and submit a Pull  Request.

**Comment by adnanebrahimi** [comment]
Sure thing. I'll give it a try!
