### ISSUE TITLE
📢 Looking for feedback

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/rx-query#2]
Hi!

Before releasing version 1, I would like to hear from you!
If you're using rx-query, I'm interested in which use-case(s) you're using it for and how it went.

Feel free to write something about your experience with rx-query, you can use the following questions as a guideline:

- was it easy to get started?
- did you like the API? What could be better?
- did it take a long time to implement the feature?
- did you also use rx-query to mutate data? 
- were you missing something? (docs/examples/feature)

**Comment by alexkunin** [comment]
Hey Tim,

I think the following is missing (or maybe it is me who's missing something): ability to just refresh the data on demand.

My use case:

* a list of records
* a "new record" form (actually it takes just two fields, the rest is filled by server)
* the list is ordered and paginated
* there is no single record view (it's pretty basic, and list row has all relevant indicators and links)

So, currently I'm using `rx-query` to manage the list, and to update the list immediately after new record is added I do whole `mutateOptimistic(...)` chain.

But due to pagination and ordering, it is hard to predict how adding new record will modify the data "optimistically" -- is new record going to end up visible in the current window? what will be its position? what items will be pushed out of view?

Instead of implementing (and supporting afterwards) all that complex logic, I'd rather do something like `refreshQuery('...')`, but there is no such functionality?

One possible way would be doing like this (`Page` is just `interface Page<T> { total: number; limit: number; skip: number; data: T[] }`):

```typescript
private readonly refreshSubject = new BehaviorSubject<void>(void 0);

readonly data$: Observable<QueryOutput<Page<Job>>> = query(
  'jobs',
  combineLatest([ this.paginationSubject, this.refreshSubject ]),
  ([ { skip, limit }, _ ]) => this.service.getJobs(limit, skip),
);

// later in the code

this.refreshSubject.next();
```

But that really looks like a long way around.

**Comment by timdeschryver** [comment]
@alexkunin thanks for the feedback! That's certainly helpful and I forgot to add it.
It's currently possible to do that, but it's not really exposed...

**Comment by alexkunin** [comment]
OK, thank you for the swift response, that sounds great!

Also, I think I found a bug (need to reproduce it reliably), some results and not coming through -- I see a successful request with new results, but view is not updated. But that will be separate issue, I guess.

**Comment by timdeschryver** [comment]
@alexkunin I think #3 is what you're asking for.
About the bug, feel free to create an issue with a reproduction (and/or if you feel like it and if you have the time, you can also [create a Pull Request](http://makeapullrequest.com/) with the fix for it).

**Comment by alexkunin** [comment]
Yes, #3 is pretty much what I was looking for, thank you very much.

Re other issue, I could not reproduce it reliably, maybe that was a mix of things. One of these things was my messy code, of course, but maybe it had some interaction with what I have described in #4 -- not a bug, strictly speaking, but somewhat unexpected behavior.

**Comment by timdeschryver** [comment]
@alexkunin `refreshQuery` and the fix for #4 are now available at `rx-query@0.0.11`.
Thanks again!

**Comment by ChristianKohler** [comment]
@timdeschryver Awesome library 🤩 

One thing I noticed: Do we always set a label? Or do we need it only for refreshing the query? If so, it would be nice to make that optional or use the return value as a reference.

**Comment by timdeschryver** [comment]
@ChristianKohler I thought I answered your question, but it seems like I didn't 😅
Yes, the label is always required because it uses the key internally, mostly to distinguish the cache entry.
For the simple cases, having the option to not provide a cache key would work (I think) but it would require more code in this library.

> If so, it would be nice to make that optional or use the return value as a reference.

What I like about the string keys, is that you can just use them everywhere (in components, in services) without a problem. I don't know how this would look like if we would use the reference. I'm open for ideas tho.

**Comment by timdeschryver** [comment]
#10 included some changes to the `mutator` to make it flexible.
I will probably release v1 of `rx-query` this month 🚀

**Comment by timdeschryver** [comment]
Thanks all for the feedback 🤗
Now that v1 is released it doesn't mean that your feedback isn't valuable anymore, so please if you have any, feel free to post it here or create a new issue for it. 🎉

**Comment by IanIsFluent** [comment]
Hi! I was looking for an angular version of react-query, so thanks so much for this!!

Just been looking at this for a couple of days and I have plenty of feedback (sorry!).

I'm usually implementing editable forms (show me a problem that can't be solved with a good form!), and I've already made a feature request issue, before coming here: https://github.com/timdeschryver/rx-query/issues/14 - sometimes the way to mutate a resource is separate to how you query it, so I feel like a top-level mutation function would be useful.

The next problem I've found is that I don't want form data to update after the page has been loaded, so I'd like a way to switch off all of the retry behaviour for a query.

But at some point, I'm going to want to allow the user to _manually_ refresh. So I'd like a way to be informed of change to the resource, and have a 'reload' button, or similar. Ideally the data would be updated, but not output immediately?

This is all achievable already with Observables, of course - but so is what this library does! ;)

**Comment by salmin89** [comment]
Hey Tim!

I am struggling with understanding how I am suppose to use the mutation when updating an item from an array. In your example you have a query that reads 1 person, and updates that 1 person. The id seems to be hard-coded as well.

Any chance you can setup a full CRUD example with https://mockapi.io/ for example?
