### ISSUE TITLE
Feature Request: return flag in  QueryOutput informing that result is from cache or fresh new

### ISSUE THREAD

**Issue by jmar5439** [timdeschryver/rx-query#27]
This feature would be very interesting im my case, because I am combining query with ngrx Effects.
if flag "from cache" would be true I will not continue action ( dispatch new reducer related action, for example)

**Comment by timdeschryver** [comment]
I think you need to perform this check manually.
When it goes to the server to get data, that data might have changed and can be different in comparison what you have in the cache. 

Fyi, there's already a difference in `state`s:
- `loading` means it's getting the data for the first time
- `refreshing` means it's getting the data in the background, while returning the current cache data

**Comment by jmar5439** [comment]
Yes @timdeschryver 
But if I configure ex query to fetch the data lets say, each 30 minutes, each time I run the query, it will return a value, cached or not. Lets say that is wrapped in a ngrx store select operation, I would not like the query to return any value, because nothing changed.

**Comment by jmar5439** [comment]
i'll show you with an example:

@Effect()
loadKanbanItemsByColumnId$ = this.actions$.pipe(
     ofType(fromActions.loadKanbanitemsByColumnId),
     mergeMap((payload) =>
     query(
      'kanban',
      payload,
        (payloadC) =>
         this.itemService.getKanbanItemsByColumnId(payloadC.columnId),       {
          staleTime: 60_000,
          cacheTime: 60_000,
        refetchOnWindowFocus: false
      }
      ).pipe(
        distinctUntilChanged(),
        filter((output) => output.status === 'success'),

// ALWAYS EMIT A VALUE HERE, EVEN IF CACHED, BUT I WOULD NOT BECAUSE ITS CACHED AND IT HASNT CHANGED
         // tap((val) => console.log('return', val)),
        map((output) =>
          fromActions.successLoadKanbanitemsSet({
            kanbanitems: output.data 
        })
         )
       )
     )
