### ISSUE TITLE
Angular 13 Support?

### ISSUE THREAD

**Issue by japfohl** [timdeschryver/rx-query#29]
Just wondering if this is compatible with Angular 13.

**Comment by timdeschryver** [comment]
To be good we should change the [compilation mode](https://angular.io/guide/angular-compiler-options#compilationmode) to 'partial'. If you want, you can create a PR for this.

**Comment by timdeschryver** [comment]
This lib doesn't depend on Angular - that's why the angular compilation mode I mentioned before doesn't matter. So yes, this lib is compatible with all versions of Angular.
