### ISSUE TITLE
Debug-tools

### ISSUE THREAD

**Issue by jordiahl** [timdeschryver/rx-query#32]
Hi great tool, coming from react query to this package is pretty seamless.

One question though, do you have any way to visualize all the queries made, or a way to debug, like some dev tools, or something I can do on the browser's dev tools to visualize the history of the queries.

**Comment by timdeschryver** [comment]
Hi @jordiahl , thanks for the feedback.
I'm not really maintaining this library anymore, and are currently no devtools.
