### ISSUE TITLE
Error on peer dependency

### ISSUE THREAD

**Issue by TimoPot** [timdeschryver/rx-query#34]
Since npm 8.6.0 peer dependencies are handled strictler.

Now we get the error below:

npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.0.0" from rx-query@1.0.2
npm ERR! node_modules/rx-query
npm ERR!   rx-query@"^1.0.2" from the root project

Please allow rx-query to work with recent versions of rxjs and update peer dependency accordingly.

**Comment by SchlammSpringer** [comment]
Part of  #37 thxs to @timdeschryver

**Comment by timdeschryver** [comment]
Should be resolved in v2.0.1
If that's not the case feel free to open a new issue.
