### ISSUE TITLE
What is the alternative?

### ISSUE THREAD

**Issue by bmarvinb** [timdeschryver/rx-query#36]
Hi, I really like this package, but if is no longer maintained, what is the alternative to pick today?

**Comment by timdeschryver** [comment]
While this library works, I don't have time to actively work on new features.
Bug fixes will be resolved, but the chance is that it can take a while.
The bigger plan was to migrate this over to [query-state](https://github.com/timdeschryver/query-state) and offer a more Angular based solution, but some things came in between...
