### ISSUE TITLE
Double subscription to params observable

### ISSUE THREAD

**Issue by alexkunin** [timdeschryver/rx-query#4]
Here is a demo: https://stackblitz.com/edit/angular-ivy-huwrze?file=src%2Fapp%2Ftest%2Ftest.component.ts

It seems that if `refetchInterval` is supplied along with params observable, then double subscription happens somewhere inside `rx-query` -- you can see two "params$ subscription" messages in console. If `refetchInterval` is commented out, only one subscription happens.

Apparently same thing happens if `refetchOnWindowFocus` is used. If both options are used, there will 3 subscriptions.

I think this behavior must be highlighted in docs -- maybe a recommendation to use `shareReplay` or similar operator. Or even better -- `rx-query` should maintain single subscription.

Alas, ATM I cannot provide a PR, as library code would need some time to get used to to confidently modify its behavior.

**Comment by timdeschryver** [comment]
Good catch!
