### ISSUE TITLE
Docs/code discrepancy

### ISSUE THREAD

**Issue by alexkunin** [timdeschryver/rx-query#5]
It seems that code requires a key, as every signature of `query()` has first parameter `key: string`: https://github.com/timdeschryver/rx-query/blob/master/rx-query/query.ts#L35

But `README.md` have some anonymous examples, e.g. `query(() => this.rickAndMortyService.getCharacters());`, and apparently they won't compile.

TBH, I'd rather have ability to make anonymous queries for simple cases where mutations etc. won't be used. As a bonus, this will render docs valid again, no changes will be required.

Again, I can't provide PR right now, though this one seems to be easier than #4, so, maybe I'll be able to do that this weekend -- given optionally anonymous queries are the way to go.

**Comment by timdeschryver** [comment]
Another good catch! The docs have examples from before rx-query had a global cache.
The key is needed to re-use query results across different instances.

For now, I want to leave the source code as is and update the docs.
This is certainly something we can re-evaluate later when this questions pops up again.
